### ISSUE TITLE
Timeout when provisioning with TPM

### ISSUE THREAD

**Issue by bkarrlander** [Azure/iotedge-eflow#127]
Some time after successful provisioning with TPM (could be a few hours or a few weeks), we experience timeouts when the devices try to provision, likely after restarts. This seems to be happening across all our EFLOW installations with TPM provisioning. Restarting the iotedge or the VM doesn't help. Only full EFLOW reinstallation with new provisioning helps.

Behavior is similar each time but the initial error message differs. We have seen at least three "flavors" of the errors:

- Failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached
- Failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'com.intel.tss2.Tabrmd': timed out (service_start_timeout=25000ms)
- Failed to create connection with service: Timeout was reached

See more details on the errors below.

## Versions

Iot Edge version: 1.1.8
EFLOW version: 1.1.2112.20121
Hyper-V version: 10.0.19041.1
Windows Host: Windows 10 Pro 20H2, 19042.1288

## Provisioning configuration:

```
provisioning:
 source: "dps"
 global_endpoint: "https://global.azure-devices-provisioning.net"
 scope_id: "<scope_id>"
 attestation:
  method: "tpm"
  registration_id: "<reg_id>"
 always_reprovision_on_startup: true
 dynamic_reprovisioning: false
```
